<a href="https://colab.research.google.com/github/Tanupanchal26/VLAUE_ADDED-COURSE/blob/main/TASK8(DATACLEANIMG_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_excel('/content/2_HR_Cleaning_Practice.xlsx')

In [3]:
df.head(10)

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
0,EMP-0152,Employee_151,Finance,4980.356928,38.0,Hybrid,5,MGR-4,2015-06-01
1,EMP-0754,Employee_753,HR,5988.381253,20.0,On-site,2,MGR-34,2017-01-23
2,EMP-1472,Employee_1471,Sales,3252.604294,30.0,Remote,1,MGR-24,2019-01-11
3,EMP-1232,Employee_1231,HR,4177.594228,6.0,Hybrid,5,MGR-7,2018-05-16
4,EMP-0022,Employee_21,Legal,273154.715607,35.0,Remote,1,MGR-13,2015-01-22

In [4]:
df.shape

(2600, 9)

In [5]:
df.columns

Index(['Employee_ID', 'Full_Name', 'Department', 'Monthly_Salary', 'Years_Exp',
       'Office_Location', 'Performance_Score', 'Manager_ID', 'Join_Date'],
      dtype='object')

In [6]:
df.head()

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
0,EMP-0152,Employee_151,Finance,4980.356928,38.0,Hybrid,5,MGR-4,2015-06-01
1,EMP-0754,Employee_753,HR,5988.381253,20.0,On-site,2,MGR-34,2017-01-23
2,EMP-1472,Employee_1471,Sales,3252.604294,30.0,Remote,1,MGR-24,2019-01-11
3,EMP-1232,Employee_1231,HR,4177.594228,6.0,Hybrid,5,MGR-7,2018-05-16
4,EMP-0022,Employee_21,Legal,273154.715607,35.0,Remote,1,MGR-13,2015-01-22

In [7]:
df.tail()

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
2595,EMP-1723,Employee_1722,Legal,4452.919905,36.0,Remote,5,MGR-8,2019-09-19
2596,EMP-1861,Employee_1860,Legal,180876.613506,13.0,Remote,5,MGR-18,2020-02-04
2597,EMP-0821,Employee_820,HR,5607.862204,21.0,On-site,1,MGR-1,2017-03-31
2598,EMP-1069,Employee_1068,Sales,5129.528837,14.0,Hybrid,4,MGR-46,2017-12-04
2599,EMP-0209,Employee_208,Legal,5657.076068,NaN,Hybrid,2,MGR-45,2015-07-28

In [8]:
df.sample(5)

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
690,EMP-1984,Employee_1983,Legal,5898.405558,13.0,On-site,5,MGR-39,2020-06-06
1654,EMP-1749,Employee_1748,Sales,250006.242312,27.0,Hybrid,3,MGR-42,2019-10-15
2375,EMP-1946,Employee_1945,HR,4253.664961,24.0,On-site,2,MGR-23,2020-04-29
2398,EMP-1948,Employee_1947,Sales,5220.053961,6.0,Remote,2,MGR-14,2020-05-01
1801,EMP-1238,Employee_1237,Finance,5228.604092,1.0,Remote,4,MGR-15,2018-05-22

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        2600 non-null   object
 1   Full_Name          2600 non-null   object
 2   Department         2600 non-null   object
 3   Monthly_Salary     2600 non-null   float64
 4   Years_Exp          2274 non-null   float64
 5   Office_Location    2600 non-null   object
 6   Performance_Score  2600 non-null   int64
 7   Manager_ID         2600 non-null   object
 8   Join_Date          2600 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 182.9+ KB

In [10]:
df.isnull()

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2595,False,False,False,False,False,False,False,False,False
2596,False,False,False,False,False,False,False,False,False
2597,False,False,False,False,False,False,False,False,False
2598,False,False,False,False,False,False,False,False,False
2599,False,False,False,False,True,False,False,False,False

In [11]:
df.isnull().sum()

Employee_ID            0
Full_Name              0
Department             0
Monthly_Salary         0
Years_Exp            326
Office_Location        0
Performance_Score      0
Manager_ID             0
Join_Date              0
dtype: int64

In [12]:
df.columns

Index(['Employee_ID', 'Full_Name', 'Department', 'Monthly_Salary', 'Years_Exp',
       'Office_Location', 'Performance_Score', 'Manager_ID', 'Join_Date'],
      dtype='object')

# HANDLING NULL **VALUES**

In [15]:
df ['Office_Location'].isnull().sum()

np.int64(0)

In [16]:
df['Department'].isnull().sum()

np.int64(0)

In [17]:
df['Years_Exp'].isnull().sum()

np.int64(326)

In [18]:
df.isnull().sum()

Employee_ID            0
Full_Name              0
Department             0
Monthly_Salary         0
Years_Exp            326
Office_Location        0
Performance_Score      0
Manager_ID             0
Join_Date              0
dtype: int64

In [20]:
df.dropna(inplace = True)

In [21]:
df.isnull().sum()

Employee_ID          0
Full_Name            0
Department           0
Monthly_Salary       0
Years_Exp            0
Office_Location      0
Performance_Score    0
Manager_ID           0
Join_Date            0
dtype: int64

In [22]:
df.shape

(2274, 9)

# **FILLING METHOD**

In [26]:
df ['Years_Exp'].head(10)

0     38.0
1     20.0
2     30.0
3      6.0
4     35.0
6     27.0
7     14.0
8     22.0
9     37.0
10    36.0
Name: Years_Exp, dtype: float64

In [27]:
df['Years_Exp'].fillna(method='ffill', inplace=True)

/tmp/ipykernel_8445/2518116019.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Years_Exp'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_8445/2518116019.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Years_Exp'].fillna(method='ffill', inplace=True)

In [28]:
df ['Years_Exp'].head(10)

0     38.0
1     20.0
2     30.0
3      6.0
4     35.0
6     27.0
7     14.0
8     22.0
9     37.0
10    36.0
Name: Years_Exp, dtype: float64

In [29]:
df['Years_Exp'].isnull().sum()

np.int64(0)

In [30]:
df['Department'].isnull().sum()

np.int64(0)

# **HANDLING DUPLICATES**

In [31]:
df.shape

(2274, 9)

In [32]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2594     True
2595     True
2596    False
2597    False
2598     True
Length: 2274, dtype: bool

In [33]:
df.duplicated().sum()

np.int64(524)

In [34]:
df.drop_duplicates(inplace=True)

In [35]:
df.shape

(1750, 9)

# HANDLING **OUTLIIERS**

In [37]:
df.head()

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
0,EMP-0152,Employee_151,Finance,4980.356928,38.0,Hybrid,5,MGR-4,2015-06-01
1,EMP-0754,Employee_753,HR,5988.381253,20.0,On-site,2,MGR-34,2017-01-23
2,EMP-1472,Employee_1471,Sales,3252.604294,30.0,Remote,1,MGR-24,2019-01-11
3,EMP-1232,Employee_1231,HR,4177.594228,6.0,Hybrid,5,MGR-7,2018-05-16
4,EMP-0022,Employee_21,Legal,273154.715607,35.0,Remote,1,MGR-13,2015-01-22

In [38]:
df.describe()

       Monthly_Salary    Years_Exp  Performance_Score
count     1750.000000  1750.000000        1750.000000
mean     16611.462885    20.586286           2.982286
std      53499.773824    11.689094           1.439548
min       2040.176787     1.000000           1.000000
25%       4371.840862    10.000000           2.000000
50%       5036.717760    21.000000           3.000000
75%       5750.641745    31.000000           4.000000
max     353179.924727    40.000000           5.000000