<a href="https://colab.research.google.com/github/Tanupanchal26/VLAUE_ADDED-COURSE/blob/main/TASK8(DATACLEANIMG_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_excel('/content/3_Healthcare_Cleaning_Practice.xlsx')

In [4]:
df.head(10)

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
0,PT-0453,Patient_452,62,O,65.695565,36.600938,126,INS-9828,2025-01-19
1,PT-0071,Patient_70,81,O,66.817837,36.995776,131,INS-5819,2025-01-03
2,PT-0156,Patient_155,5,O,59.934299,36.790915,128,INS-1923,2025-01-07
3,PT-1479,Patient_1478,89,F,76.003233,36.912039,134,INS-1421,2025-03-03
4,PT-0308,Patient_307,39,O,62.876117,37.873569,138,INS-3626,2025-01-13
5,PT-0838,Patient_837,72,O,68.780750,36.758493,132,INS-5740,2025-02-04
6,PT-1114,Patient_1113,5,F,78.699509,36.437192,137,INS-7740,2025-02-16
7,PT-0997,Patient_996,35,O,71.971583,36.917084,112,INS-2450,2025-02-11
8,PT-1115,Patient_1114,27,F,56.175907,37.576177,121,INS-4230,2025-02-16
9,PT-0406,NaN,76,F,75.526463,37.080721,118,INS-1834,2025-01-17

In [5]:
df.shape

(2600, 9)

In [6]:
df.columns

Index(['Patient_ID', 'Patient_Name', 'Age', 'Gender', 'Heart_Rate',
       'Body_Temp_C', 'Blood_Pressure_Sys', 'Insurance_ID', 'Last_Checkup'],
      dtype='object')

In [7]:
df.head()

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
0,PT-0453,Patient_452,62,O,65.695565,36.600938,126,INS-9828,2025-01-19
1,PT-0071,Patient_70,81,O,66.817837,36.995776,131,INS-5819,2025-01-03
2,PT-0156,Patient_155,5,O,59.934299,36.790915,128,INS-1923,2025-01-07
3,PT-1479,Patient_1478,89,F,76.003233,36.912039,134,INS-1421,2025-03-03
4,PT-0308,Patient_307,39,O,62.876117,37.873569,138,INS-3626,2025-01-13

In [8]:
df.tail()

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
2595,PT-1391,Patient_1390,1,M,450.000000,36.672493,116,INS-9630,2025-02-27
2596,PT-1349,Patient_1348,85,O,70.755489,37.353741,134,INS-3252,2025-02-26
2597,PT-0112,Patient_111,54,M,74.202918,37.416936,123,INS-5483,2025-01-05
2598,PT-0301,NaN,83,O,63.195318,36.219781,140,INS-7665,2025-01-13
2599,PT-1225,Patient_1224,73,M,74.383926,36.310635,139,INS-3402,2025-02-21

In [9]:
df.sample(5)

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
2322,PT-0089,Patient_88,21,M,73.290763,35.864838,135,INS-1373,2025-01-04
108,PT-1252,Patient_1251,70,O,75.754464,37.333977,127,INS-5126,2025-02-22
1993,PT-0568,Patient_567,88,F,70.060606,36.805037,119,INS-4417,2025-01-24
2239,PT-0179,Patient_178,5,F,70.657149,37.697388,116,INS-2628,2025-01-08
1906,PT-0053,Patient_52,62,F,54.172794,36.983605,124,INS-4666,2025-01-03

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          2600 non-null   object
 1   Patient_Name        2429 non-null   object
 2   Age                 2600 non-null   int64
 3   Gender              2600 non-null   object
 4   Heart_Rate          2600 non-null   float64
 5   Body_Temp_C         2600 non-null   float64
 6   Blood_Pressure_Sys  2600 non-null   int64
 7   Insurance_ID        2600 non-null   object
 8   Last_Checkup        2600 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 182.9+ KB

In [11]:
df.isnull()

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2595,False,False,False,False,False,False,False,False,False
2596,False,False,False,False,False,False,False,False,False
2597,False,False,False,False,False,False,False,False,False
2598,False,True,False,False,False,False,False,False,False
2599,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

Patient_ID              0
Patient_Name          171
Age                     0
Gender                  0
Heart_Rate              0
Body_Temp_C             0
Blood_Pressure_Sys      0
Insurance_ID            0
Last_Checkup            0
dtype: int64

In [ ]:
df.columns

# HANDLING NULL **VALUES**

In [13]:
df ['Age'].isnull().sum()

np.int64(0)

In [18]:
df['Patient_Name'].isnull().sum()

np.int64(171)

In [16]:
df['Last_Checkup'].isnull().sum()

np.int64(0)

In [17]:
df.isnull().sum()

Patient_ID              0
Patient_Name          171
Age                     0
Gender                  0
Heart_Rate              0
Body_Temp_C             0
Blood_Pressure_Sys      0
Insurance_ID            0
Last_Checkup            0
dtype: int64

In [19]:
df.dropna(inplace = True)

In [20]:
df.isnull().sum()

Patient_ID            0
Patient_Name          0
Age                   0
Gender                0
Heart_Rate            0
Body_Temp_C           0
Blood_Pressure_Sys    0
Insurance_ID          0
Last_Checkup          0
dtype: int64

In [21]:
df.shape

(2429, 9)

# FILLING **METHOD**

In [24]:
df ['Patient_Name'].head(10)

0      Patient_452
1       Patient_70
2      Patient_155
3     Patient_1478
4      Patient_307
5      Patient_837
6     Patient_1113
7      Patient_996
8     Patient_1114
10    Patient_1351
Name: Patient_Name, dtype: object

In [23]:
df['Patient_Name'].fillna(method='ffill', inplace=True)

/tmp/ipykernel_286/4169607986.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Patient_Name'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_286/4169607986.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Patient_Name'].fillna(method='ffill', inplace=True)

In [25]:
df ['Patient_Name'].head(10)

0      Patient_452
1       Patient_70
2      Patient_155
3     Patient_1478
4      Patient_307
5      Patient_837
6     Patient_1113
7      Patient_996
8     Patient_1114
10    Patient_1351
Name: Patient_Name, dtype: object

# **HANDLING DUPLICATES**

In [27]:
df.shape

(2429, 9)

In [26]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2594    False
2595    False
2596     True
2597     True
2599     True
Length: 2429, dtype: bool

In [28]:
df.duplicated().sum()

np.int64(563)

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df.shape

(1866, 9)

# **HANDLING OUTLIIERS**

In [31]:
df.head()

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
0,PT-0453,Patient_452,62,O,65.695565,36.600938,126,INS-9828,2025-01-19
1,PT-0071,Patient_70,81,O,66.817837,36.995776,131,INS-5819,2025-01-03
2,PT-0156,Patient_155,5,O,59.934299,36.790915,128,INS-1923,2025-01-07
3,PT-1479,Patient_1478,89,F,76.003233,36.912039,134,INS-1421,2025-03-03
4,PT-0308,Patient_307,39,O,62.876117,37.873569,138,INS-3626,2025-01-13

In [32]:
df.describe()

               Age   Heart_Rate  Body_Temp_C  Blood_Pressure_Sys
count  1866.000000  1866.000000  1866.000000         1866.000000
mean     48.292069    77.804499    37.010791          124.862272
std      27.567823    46.612438     0.494420            8.878555
min       1.000000    47.730630    35.479147          110.000000
25%      25.000000    67.013489    36.677279          117.000000
50%      49.000000    72.249923    37.009642          125.000000
75%      72.000000    77.563966    37.359660          133.000000
max      95.000000   450.000000    38.853324          140.000000